
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohwnivmumeobkrhppdvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9od25pdm11bWVvYmtyaHBwZHZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDc1MjEsImV4cCI6MjA2MjYyMzUyMX0.1nAozlIHCMGdA-nuU8zneRZ9BnY23b4FwnYAeEa6SLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
