// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptfukupojjepayskixtu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0ZnVrdXBvamplcGF5c2tpeHR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDkzMjEsImV4cCI6MjA2MDI4NTMyMX0.aHhSEJtrCN4Y4Vqg2lPGLOGdd8RWjLIsLY9NzGowUTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);